User can view items on Bespoken Words.
Stevenlee731/bespoken-words pull request #2
Opened 2017-03-15 16:42 UTC by Stevenlee731

2017-03-15 17:22 UTC, thebearingedge requested changes

2017-03-15 17:22 UTC, thebearingedge commented on main.js
> +items.forEach(function(item) {
Hi Steve, you should create a separate function to render the `$item` and call that function in your `forEach`.

2017-03-15 18:50 UTC, thebearingedge commented on main.js
> +items.forEach(function(item) {
```js
var $items = document.querySelector('#items')

items.forEach(function (item) {
  var $item = renderItem(item)
  $items.appendChild($item)
})
```

2017-03-15 21:01 UTC, Stevenlee731 commented on main.js
> +items.forEach(function(item) {
added the changes!

2017-03-16 00:10 UTC, Stevenlee731 reviewed
Made the changes you requested

2017-03-16 00:10 UTC, Stevenlee731 commented on main.js
> +items.forEach(function(item) {
Made the changes!

2017-03-16 19:46 UTC, merged